package com.giangvdm.myebaycompanionapp.view;

import com.giangvdm.myebaycompanionapp.controller.DataController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author giangvdm
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        try {
            DataController dataCtl = new DataController();
            dataCtl.getCurrencyRatesConfig();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        paneObservedItems = new javax.swing.JPanel();
        paneCalculator = new javax.swing.JPanel();
        paneConfig = new javax.swing.JPanel();
        labelCurrencyRates = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelVND = new javax.swing.JLabel();
        labelUSD = new javax.swing.JLabel();
        spinnerUSD = new javax.swing.JSpinner();
        labelEUR = new javax.swing.JLabel();
        spinnerEUR = new javax.swing.JSpinner();
        labelGBP = new javax.swing.JLabel();
        spinnerGBP = new javax.swing.JSpinner();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Ebay Companion App");

        javax.swing.GroupLayout paneObservedItemsLayout = new javax.swing.GroupLayout(paneObservedItems);
        paneObservedItems.setLayout(paneObservedItemsLayout);
        paneObservedItemsLayout.setHorizontalGroup(
            paneObservedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        paneObservedItemsLayout.setVerticalGroup(
            paneObservedItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Observed Items", paneObservedItems);

        javax.swing.GroupLayout paneCalculatorLayout = new javax.swing.GroupLayout(paneCalculator);
        paneCalculator.setLayout(paneCalculatorLayout);
        paneCalculatorLayout.setHorizontalGroup(
            paneCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        paneCalculatorLayout.setVerticalGroup(
            paneCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Calculator", paneCalculator);

        labelCurrencyRates.setText("Currency Rates");

        labelVND.setText("VND");

        labelUSD.setText("USD");

        spinnerUSD.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        labelEUR.setText("EUR");

        spinnerEUR.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        labelGBP.setText("GBP");

        spinnerGBP.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        javax.swing.GroupLayout paneConfigLayout = new javax.swing.GroupLayout(paneConfig);
        paneConfig.setLayout(paneConfigLayout);
        paneConfigLayout.setHorizontalGroup(
            paneConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(paneConfigLayout.createSequentialGroup()
                        .addComponent(labelCurrencyRates)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneConfigLayout.createSequentialGroup()
                        .addComponent(labelVND)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerEUR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(paneConfigLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(labelUSD)
                .addGap(96, 96, 96)
                .addComponent(labelEUR)
                .addGap(99, 99, 99)
                .addComponent(labelGBP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneConfigLayout.setVerticalGroup(
            paneConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCurrencyRates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(paneConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUSD)
                    .addComponent(labelEUR)
                    .addComponent(labelGBP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerEUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVND)
                    .addComponent(spinnerUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Config", paneConfig);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCurrencyRates;
    private javax.swing.JLabel labelEUR;
    private javax.swing.JLabel labelGBP;
    private javax.swing.JLabel labelUSD;
    private javax.swing.JLabel labelVND;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel paneCalculator;
    private javax.swing.JPanel paneConfig;
    private javax.swing.JPanel paneObservedItems;
    private javax.swing.JSpinner spinnerEUR;
    private javax.swing.JSpinner spinnerGBP;
    private javax.swing.JSpinner spinnerUSD;
    // End of variables declaration//GEN-END:variables
}
